# repos:
#   - repo: https://github.com/vkseth/vfde-pre-commit-hooks
#     rev: v2.3.4
#     hooks:
#       - id: tflint

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: tflint

